version: '3.8'

services:
  # Nosso Banco de Dados (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: portfolio-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: portfoliodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Configuração do seu Backend (NestJS)
  server:
    build: ./server
    ports:
      - "3000:3000" 
    depends_on:
      - postgres 

  # Configuração do seu Frontend (Vite/React)
  client:
    build: ./client
    ports:
      - "5173:5173" 
    depends_on:
      - server 

# Mapeamento do HD virtual do banco de dados para não perder os dados
volumes:
  postgres_data: